version: '3.7'

services:
    db:
        restart: always
        image: postgres:12-alpine
        ports:
            - '5434:5432'
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        env_file:
            - .env


volumes:
    postgres_data:
